### ISSUE TITLE
Implementation plan

### ISSUE THREAD

**Issue by Yeongtae** [m-toman/tacorn#10]
## Data feeding
- <del>[ ]  using parameters in hparam.py to reduce independent parameters (3rd)<del>
- <del>[ ]  muLaw quantization to preserve more important information (4th) <del>
## Model 
- [x] <del> modifying the wavernn model to reduce matrix multiflications (1st, ~ 11.04) **(Fail)**
- [ ] test half precision and holding on network parameters on half precision register. (extended 1st, ~<del>11.11</del> 11.14)
- <del>[ ]  weight sparsification to reduce computation times (2nd, ~11.16)<del>

**Comment by bjtommychen** [comment]
Thanks you both. I am looking forward to your progress.

**Comment by m-toman** [comment]
Thanks for the experiment. Unfortunately I'm in hospital and couldn't continue to integrate the original wavernn implementation for now, but it's still on my agenda.

**Comment by Yeongtae** [comment]
I'm trying to use faster wave generator, which is waveglow.
Sorry about stopping implementation.

**Comment by m-toman** [comment]
Perhaps this post is interesting for you: https://github.com/mozilla/TTS/issues/9#issuecomment-440976514
I'm generally still watching the Mozilla TTS repo to check their progress with WaveRNN.

**Comment by m-toman** [comment]
I'll close this for now.
