### ISSUE TITLE
How much work would it take to make this real-world ready?

### ISSUE THREAD

**Issue by ishansan38** [m-toman/tacorn#12]
Hi @m-toman Great work on the repo, the results looks promising. What all work do you think this repo would need to make this real-world useful someday?

**Comment by m-toman** [comment]
Hi, depends a lot on the use case regarding performance, quality and platform requirements.
For fully offline synthesis I guess you should be able to use the Wavenet implementation in the taco2 repo, or in combination with r9y9 Wavenet vocoder.

The ultimate goal for this repo (for now) is to assess WaveRNN as a middle-ground between Wavenet and traditional Vocoders.
