### ISSUE TITLE
Dropbox links are dead

### ISSUE THREAD

**Issue by babon** [m-toman/tacorn#14]
Pre trained models in install.sh return 404:
 https://www.dropbox.com/s/86fiurfwbv4b2hp/tacorn_wavernn.pyt
 https://www.dropbox.com/s/y49ppvkkto79hct/tacorn_wavernn_step.npy

**Comment by m-toman** [comment]
Right, the newer mechanism (when downloading via create.py) uses those links:
https://github.com/m-toman/tacorn/blob/master/tacorn/constants.py
They should most likely still work with this repo, but as I moved on once again ;), I can't give guarantees.
