### ISSUE TITLE
Clarification on WaveRNN

### ISSUE THREAD

**Issue by Vproject** [m-toman/tacorn#4]
If I understand correctly, @fatchord's Alternative Model is quite different from WaveRNN and not just a modification on it. So perhaps it would be better to avoid referring to it as WaveRNN to avoid confusion and to avoid implicitly crediting the creators of WaveRNN with what might more accurately be attributed to @fatchord.

**Comment by m-toman** [comment]
Fair enough, when I started out I actually wanted to use WaveRNN and then picked the alternative model by @fatchord. As there is no official name, I revised the descriptions to fatchord's WaveRNN-inspired method ;).
