### ISSUE TITLE
bits=9 -> 16, Is it OK?

### ISSUE THREAD

**Issue by chkwon1** [m-toman/tacorn#6]
I modified bits=9 to 16 in wavernn/preprocess.py and model.py.
By this modification your code is working.
Do you think the synthesized speech quality can be improved?

**Comment by m-toman** [comment]
Well, the model is created by https://github.com/fatchord/WaveRNN and not me, but I suspect that there are probably too few model parameters for that.
Still, might be worth a try.

**Comment by chkwon19** [comment]
close #6

**Comment by m-toman** [comment]
Will be solved once we have #8
