### ISSUE TITLE
which tf version you use? thanks.

### ISSUE THREAD

**Issue by bjtommychen** [m-toman/tacorn#9]
when load checkpoint file.
Key Tacotron_model/inference/CBHG_postnet/CBHG_postnet_highwaynet_1/H/bias not found in checkpoint

**Comment by m-toman** [comment]
My uploaded model wasn't compatible with the latest Tacotron-2 version.
I'm uploading a new one at the moment.

TF 1.10 works for me, but in general TF is just needed for Tacotron - so the requirements from https://github.com/Rayhane-mamah/Tacotron-2/ are relevant.

**Comment by bjtommychen** [comment]
thanks for your quick answer. 
it work with latest Tacotron-2 !

**Comment by m-toman** [comment]
If you need it, the new English base model (LJ) is uploaded with the same URL. Didn't try it yet though, it's at 70k steps of the current Tacotron-2 repo with default hparams.

**Comment by bjtommychen** [comment]
btw, the LJ-WaveRNN failed to work with your LJ-Tacotron.
but my trained WaveRNN work with it well.

**Comment by m-toman** [comment]
Did it produce noise or failed to load.
I'm currently training that as well

**Comment by bjtommychen** [comment]
silence, with some flick.

**Comment by m-toman** [comment]
Ok they probably changed some params for the Mel represention, I also started the training for that from scratch and should have 1000 epochs done later today.
